x-shared: &shared
  image: yukaichong/news-matching:latest
  volumes:
    - "./data:/usr/src/app/data"
    - "./trained_models:/usr/src/app/trained_models"
    - "./cached_models:/usr/src/app/cached_models"
  environment:
    - USER_ID=1000
    - GROUP_ID=1000
    - TZ=Asia/Singapore
    - GSHEET_TAXONOMY_ID=<GSHEET_TAXONOMY_ID>
    - GCS_BUCKET=<GCS_BUCKET>
    - 'GOOGLE_APPLICATION_CREDENTIALS_JSON=<GOOGLE_APPLICATION_CREDENTIALS>'

services:
  streamlit:
    <<: *shared
    ports:
      - "8501:8501"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      TZ: Asia/Singapore
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: "0 0 17 * * *" # Check update every day 5pm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
