x-shared:
  &shared
  image: news-matching
  volumes:
    - './data:/usr/src/app/data'
    - './trained_models:/usr/src/app/trained_models'
    - './cached_models:/usr/src/app/cached_models'

services:
  streamlit:
    <<: *shared
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '8501:8501'
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    restart: unless-stopped
  # scheduler:
  #   <<: *shared
  #   depends_on:
  #     - streamlit
  #   restart: unless-stopped
  #   # command: python ...

  #   # docker compose up -d
